using Microsoft.EntityFrameworkCore;

namespace KhanHomeFloralLine.Infrastructure.Persistence;

public static class IdentitySchemaBootstrapper
{
    public static async Task EnsureAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        var sql = @"
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""UserName"" character varying(256);
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""NormalizedUserName"" character varying(256);
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""NormalizedEmail"" character varying(256);
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""EmailConfirmed"" boolean NOT NULL DEFAULT false;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""SecurityStamp"" text;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""ConcurrencyStamp"" text;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""PhoneNumber"" text;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""PhoneNumberConfirmed"" boolean NOT NULL DEFAULT false;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""TwoFactorEnabled"" boolean NOT NULL DEFAULT false;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""LockoutEnd"" timestamp with time zone;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""LockoutEnabled"" boolean NOT NULL DEFAULT false;
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""AccessFailedCount"" integer NOT NULL DEFAULT 0;
ALTER TABLE ""Users"" ALTER COLUMN ""Phone"" DROP NOT NULL;

UPDATE ""Users"" SET ""UserName"" = COALESCE(""UserName"", ""Email"") WHERE ""Email"" IS NOT NULL;
UPDATE ""Users"" SET ""NormalizedUserName"" = COALESCE(""NormalizedUserName"", UPPER(""UserName"")) WHERE ""UserName"" IS NOT NULL;
UPDATE ""Users"" SET ""NormalizedEmail"" = COALESCE(""NormalizedEmail"", UPPER(""Email"")) WHERE ""Email"" IS NOT NULL;
UPDATE ""Users"" SET ""PhoneNumber"" = COALESCE(""PhoneNumber"", ""Phone"") WHERE ""Phone"" IS NOT NULL;

CREATE TABLE IF NOT EXISTS ""Roles"" (
    ""Id"" uuid NOT NULL,
    ""Name"" character varying(256),
    ""NormalizedName"" character varying(256),
    ""ConcurrencyStamp"" text,
    CONSTRAINT ""PK_Roles"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS ""RoleClaims"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""RoleId"" uuid NOT NULL,
    ""ClaimType"" text,
    ""ClaimValue"" text,
    CONSTRAINT ""PK_RoleClaims"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_RoleClaims_Roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""UserClaims"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" uuid NOT NULL,
    ""ClaimType"" text,
    ""ClaimValue"" text,
    CONSTRAINT ""PK_UserClaims"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_UserClaims_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""UserLogins"" (
    ""LoginProvider"" text NOT NULL,
    ""ProviderKey"" text NOT NULL,
    ""ProviderDisplayName"" text,
    ""UserId"" uuid NOT NULL,
    CONSTRAINT ""PK_UserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
    CONSTRAINT ""FK_UserLogins_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""UserRoles"" (
    ""UserId"" uuid NOT NULL,
    ""RoleId"" uuid NOT NULL,
    CONSTRAINT ""PK_UserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
    CONSTRAINT ""FK_UserRoles_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_UserRoles_Roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""UserTokens"" (
    ""UserId"" uuid NOT NULL,
    ""LoginProvider"" text NOT NULL,
    ""Name"" text NOT NULL,
    ""Value"" text,
    CONSTRAINT ""PK_UserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
    CONSTRAINT ""FK_UserTokens_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ""IX_Users_NormalizedEmail"" ON ""Users"" (""NormalizedEmail"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_NormalizedUserName"" ON ""Users"" (""NormalizedUserName"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Roles_NormalizedName"" ON ""Roles"" (""NormalizedName"");
CREATE INDEX IF NOT EXISTS ""IX_RoleClaims_RoleId"" ON ""RoleClaims"" (""RoleId"");
CREATE INDEX IF NOT EXISTS ""IX_UserClaims_UserId"" ON ""UserClaims"" (""UserId"");
CREATE INDEX IF NOT EXISTS ""IX_UserLogins_UserId"" ON ""UserLogins"" (""UserId"");
CREATE INDEX IF NOT EXISTS ""IX_UserRoles_RoleId"" ON ""UserRoles"" (""RoleId"");
";

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}

